/**
 * @file    app_globals.h
 * @brief   Shared application types, buffers, queue handles, and task handles.
 *
 * All data that crosses task boundaries is declared here.
 * Source definitions live in app_globals.c.
 */

#ifndef INC_APP_GLOBALS_H_
#define INC_APP_GLOBALS_H_

#include "cmsis_os.h"
#include "board_config.h"
#include "rf_waveform_classifier.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

/* =========================================================================
 * BUTTON STATE  (updated by Task_PollButton_Run every 10 ms)
 * true = currently pressed
 * ========================================================================= */
typedef struct {
    bool menu1;
    bool menu2;
    bool menu3;
    bool enter;
    bool up;
    bool down;
    bool left;
    bool right;
} ButtonStates_t;

extern volatile ButtonStates_t g_btn;

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 * SHARED PERIPHERAL HANDLES
 * hadc2 / hdma_adc2 are generated by CubeMX and defined in main.c.
 * htim_adc is defined in app_globals.c.
 * ========================================================================= */
extern ADC_HandleTypeDef  hadc1;      /* ADC1 — current sense (PA3 / IN4) */
extern ADC_HandleTypeDef  hadc2;
extern DMA_HandleTypeDef  hdma_adc2;
extern TIM_HandleTypeDef  htim_adc;   /* TIM2 — ADC trigger master */

/* =========================================================================
 * DISPLAY COMMAND TYPES
 * ========================================================================= */
typedef enum {
    DISP_CMD_WAVEFORM  = 0,
    DISP_CMD_CURRENT,
    DISP_CMD_FFT,
    DISP_CMD_CURVEFIT,
    DISP_CMD_STATUS,
    DISP_CMD_CLEAR,
} DisplayCmdType_t;

typedef struct {
    DisplayCmdType_t type;
    uint32_t         param;
} DisplayCmd_t;

/* =========================================================================
 * MEASUREMENT MODE
 * ========================================================================= */
typedef enum {
    MEAS_MODE_LV   = 0,
    MEAS_MODE_HV,
    MEAS_MODE_CURR,
} MeasMode_t;

/* =========================================================================
 * CURVE FIT RESULT
 * ========================================================================= */
typedef struct {
    float amplitude;
    float frequency;
    float phase_rad;
    float dc_offset;
    float rmse;
    bool  valid;
} CurveFitResult_t;

/* =========================================================================
 * SHARED ADC SAMPLE BUFFERS
 * Single-channel DMA fills g_voltage_buf[] directly (no interleaving on G4).
 * g_dma_adc_buf kept for API compatibility with downstream tasks.
 * ========================================================================= */
extern uint16_t g_voltage_buf[ADC_BUFFER_SIZE];   /* DMA destination  */
extern uint32_t g_adc_buf_len;
extern uint16_t g_current_raw;                    /* latest raw ADC count from current sense */

/* =========================================================================
 * FFT OUTPUT BUFFER
 * ========================================================================= */
extern float g_fft_mag[ADC_BUFFER_SIZE / 2];
extern float g_fft_peak_freq_hz;
extern float g_fft_peak_mag;

/* =========================================================================
 * CURVE FIT RESULT
 * ========================================================================= */
extern CurveFitResult_t g_fit_result;

/* =========================================================================
 * WAVEFORM CLASSIFIER RESULT  (updated by Task_FFT_Run after each FFT)
 * Protected by xFFTBufMutex.
 * ========================================================================= */
extern RF_Result_t g_rf_result;

/* =========================================================================
 * APPLICATION STATE
 * ========================================================================= */
extern volatile MeasMode_t g_meas_mode;
extern volatile bool       g_paused;        /* true = paused, false = playing */
extern volatile int8_t     g_zoom_level;    /* -3=8x out … 0=1x … +3=8x in */
extern volatile int32_t    g_pan_y_counts;     /* vertical pan offset in ADC counts */
extern volatile int32_t    g_pan_x_samples;    /* horizontal pan offset in samples */
extern volatile uint32_t   g_adc_capture_tick; /* HAL_GetTick() at last DMA complete */

/* =========================================================================
 * FREERTOS HANDLES
 * ========================================================================= */
extern osMessageQueueId_t xDisplayCmdQueue;
extern osMutexId_t        xADCBufMutex;
extern osMutexId_t        xFFTBufMutex;

extern osThreadId_t hVoltageADCTask;
extern osThreadId_t hCurrentADCTask;
extern osThreadId_t hFFTTask;
extern osThreadId_t hDisplayTask;
extern osThreadId_t hCurveFitTask;
extern osThreadId_t hDACTask;

/* =========================================================================
 * NOTIFICATION BIT MASKS
 * ========================================================================= */
#define NOTIF_ADC_BUF_READY     (1U << 0)
#define NOTIF_ADC_HALF_READY    (1U << 1)

/* =========================================================================
 * VOLTAGE SCALING
 * actual_V = 13.200 * adc_V - 19.54
 * ========================================================================= */
#define VSCALE_SLOPE_PPM   13200L
#define VSCALE_OFFSET_MV   -19740L

static inline int32_t count_to_actual_mv(uint16_t count)
{
    int32_t adc_mv = (int32_t)((uint32_t)count * ADC_VREF_MV / ADC_MAX_COUNT);
    return adc_mv * (int32_t)VSCALE_SLOPE_PPM / 1000L + VSCALE_OFFSET_MV;
}

static inline void fmt_mv(char *buf, size_t n, int32_t mv)
{
    int32_t amv = mv < 0 ? -mv : mv;
    snprintf(buf, n, "%s%ld.%ldV",
             mv < 0 ? "-" : "",
             (long)(amv / 1000), (long)(amv % 1000 / 100));
}

/* =========================================================================
 * INITIALISATION
 * ========================================================================= */
void App_Globals_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* INC_APP_GLOBALS_H_ */
